name: 'Deploy to S3'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.17"

      - name: Install Node.js dependencies
        run: yarn install

      - name: Build Project
        env:
          CI: false
        run: yarn build

      - name: Upload to S3
        run: |
          aws s3 sync build s3://infinitebitsband.com/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id EADATL1B0O6CM --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
